/*
 * File: app/view/RegistrationView.js
 * Date: Sat Jul 13 2013 17:15:08 GMT+0530 (Sri Lanka Standard Time)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RoadPech.view.RegistrationView', {
    extend: 'Ext.form.Panel',
    alias: 'widget.registrationView',

    singleton: true,

    config: {
        fullscreen: true,
        trackResetOnLoad: true,
        items: [
            {
                xtype: 'label',
                hidden: true,
                hideAnimation: 'fadeOut',
                html: 'Login failed. Please enter the correct credentials.',
                itemId: 'signInFailedLabel',
                showAnimation: 'fadeIn',
                style: 'color:#990000;margin:5px 0px;'
            },
            {
                xtype: 'fieldset',
                height: '100%',
                id: 'regTitle',
                title: 'Register',
                items: [
                    {
                        xtype: 'textfield',
                        id: 'username',
                        label: 'Name'
                    },
                    {
                        xtype: 'emailfield',
                        id: 'email',
                        label: 'Email',
                        placeHolder: 'email@example.com'
                    },
                    {
                        xtype: 'passwordfield',
                        id: 'password',
                        label: 'Password'
                    },
                    {
                        xtype: 'container',
                        defaults: {
                            style: 'margin : .5em'
                        },
                        layout: {
                            align: 'center',
                            pack: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                flex: 1,
                                itemId: 'btnNo',
                                ui: 'decline',
                                text: 'Reset'
                            },
                            {
                                xtype: 'button',
                                flex: 1,
                                id: '',
                                itemId: 'btnYes',
                                ui: 'confirm',
                                text: 'Register'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});