/*
 * File: app/controller/Main.js
 * Date: Sun Jul 14 2013 03:44:00 GMT+0530 (Sri Lanka Standard Time)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RoadPech.controller.Main', {
    extend: 'Ext.app.Controller',

    config: {
        models: [
            'User'
        ],
        stores: [
            'Users'
        ],
        views: [
            'MainWindow',
            'Welcome'
        ],

        routes: {
            '': 'welcome',
            'map': 'mapHandler'
        },

        refs: {
            welcomeScreen: 'welcomePanel'
        }
    },

    welcome: function() {
        var isShown = eval(localStorage.showWelcomeScreen);
        isShown = isShown==undefined ? true : isShown;
        console.log(isShown);
        if (isShown){
            Ext.Viewport.setActiveItem(this.getWelcomeScreen());
        }else{
            this.destroy();
            this.redirectTo("map");
        }


    },

    mapHandler: function() {

    }

});